FROM node:13 AS dashboard
COPY ./dashboard /frontend
WORKDIR /frontend
RUN npm install
RUN npm run build

FROM ruby:2.7
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev postgresql-client
RUN mkdir /app
WORKDIR /app
ENV HOST_DASHBOARD /app/public/
COPY Gemfile /app/Gemfile
COPY Gemfile.lock /app/Gemfile.lock
RUN bundle install
COPY . /app
COPY --from=dashboard /frontend/dist ./public

ENTRYPOINT [ "bash", "./entrypoint.sh"]
